### ISSUE TITLE
Errors when running UDregenerator

### ISSUE THREAD

**Issue by DraymondHIT** [rali-udem/jsRealB#47]
I tried to run [UDregenerator](https://github.com/rali-udem/jsRealB/tree/master/demos/UDregenerator) in Colab. When I ran
```
!node variationsFromText.js file.txt
```
I met following errors.
```
*** Creating file.conllu
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn ./text2ud.py EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn ./text2ud.py',
  path: './text2ud.py',
  spawnargs: [ 'en', 'file.txt' ]
}
```
What do these information mean? How could I fix with it?

**Comment by lapalme** [comment]
Kunze

there seems to be a problem when you are launching "text2ud.py" which takes for granted that "Stanza" (the Stanford dependency parser) is already installed. I suggest the you test "text2ud.py" alone before you try using it from "variationsFromText.js"

Guy

**Comment by DraymondHIT** [comment]
Thank you, Guy!

I'm not sure where the problems lie. Today, I ran it again on my [colab notebook](https://colab.research.google.com/drive/1rOE-3zwe-rv7rCT87XW12LhRLoz_h2ec?usp=sharing), it works well. When I ran
```
!node variationsFromText.js -q file.txt
```
results were as follows.
```
# id   = 1.0
# text = The white cat sits on the mat.
# TEXT = The white cat sits on the mat. 
# WAS  = What sits on the mat?  => the white cat
# WAD  = What does the white cat sit?  => on the mat

1 UD dependencies processed
2 questions
```

Anyway, thanks for your help!!!

**Comment by lapalme** [comment]
Kunze

great! if you need the dependency trees themselves, you can add the the "-t" option to the call to variationsFromText.js

Guy
