### ISSUE TITLE
Error using `fromJSON` with `own` property

### ISSUE THREAD

**Issue by simonvarey** [rali-udem/jsRealB#52]
If you run `fromJSON(D("my").pe(2).ow("s").toJSON(), 'en')` you will get the error 'Constituent.fromJSON: illegal prop:own'. The issue seems to be with the definition of the `own` option at https://github.com/rali-udem/jsRealB/blob/master/src/Constituent.js#L643 where, unlike any other property, `own` gets an `optionName` different from its `option`. I think this issue could be fixed by moving https://github.com/rali-udem/jsRealB/blob/master/src/Constituent.js#L578 earlier, but I haven't checked this.

**Comment by lapalme** [comment]
Simon
I have fix this with a few other things that came up when I tested other examples.
thanks for your feedback
Guy
